import { BACKGAMMON_TYPES } from 'types';

export default [
    // Top left.
    [BACKGAMMON_TYPES.PLAYERS.WHITE, 2],
    [BACKGAMMON_TYPES.PLAYERS.NONE, 0],
    [BACKGAMMON_TYPES.PLAYERS.NONE, 0],
    [BACKGAMMON_TYPES.PLAYERS.NONE, 0],
    [BACKGAMMON_TYPES.PLAYERS.NONE, 0],
    [BACKGAMMON_TYPES.PLAYERS.BLACK, 5],

    // Top right.

    [BACKGAMMON_TYPES.PLAYERS.NONE, 0],
    [BACKGAMMON_TYPES.PLAYERS.BLACK, 3],
    [BACKGAMMON_TYPES.PLAYERS.NONE, 0],
    [BACKGAMMON_TYPES.PLAYERS.NONE, 0],
    [BACKGAMMON_TYPES.PLAYERS.NONE, 0],
    [BACKGAMMON_TYPES.PLAYERS.WHITE, 5],

    // Bottom right.

    [BACKGAMMON_TYPES.PLAYERS.BLACK, 5],
    [BACKGAMMON_TYPES.PLAYERS.NONE, 0],
    [BACKGAMMON_TYPES.PLAYERS.NONE, 0],
    [BACKGAMMON_TYPES.PLAYERS.NONE, 0],
    [BACKGAMMON_TYPES.PLAYERS.WHITE, 3],
    [BACKGAMMON_TYPES.PLAYERS.NONE, 0],

    // Bottom left.

    [BACKGAMMON_TYPES.PLAYERS.WHITE, 5],
    [BACKGAMMON_TYPES.PLAYERS.NONE, 0],
    [BACKGAMMON_TYPES.PLAYERS.NONE, 0],
    [BACKGAMMON_TYPES.PLAYERS.NONE, 0],
    [BACKGAMMON_TYPES.PLAYERS.BLACK, 1],
    [BACKGAMMON_TYPES.PLAYERS.BLACK, 1],
];
