import { Game } from "./backgammon";

export enum GAME_EVENTS {
    JOIN_GAME = "JOIN_GAME",
    DISCONNECT_USER = "DISCONNECT_USER",
    DISCONNECT_PLAYER = "DISCONNECT_PLAYER",
    INITIALIZE_GAME = "INITIALIZE_GAME",
    ROUND = "ROUND",
    BROKEN_POINT_ROUND = "BROKEN_POINT_ROUND",
    ERROR = "ERROR",
    BAD_REQUEST = "BAD_REQUEST",
    STAGE_OVER = "STAGE_OVER",
    SKIP_ROUND = "SKIP_ROUND",
    SHORT_TIMER = "SHORT_TIMER",
    TIMER = "TIMER",
}

export type EmitGame = Game;
